"""
repo-graph generator.

Orchestrates language-specific analyzers to produce:
  - nodes.json   — all discovered entities
  - edges.json   — directed relationships between entities
  - flows/*.yaml — end-to-end request paths per feature
  - state.md     — session-start snapshot

Usage:
    repo-graph-generate --repo /path/to/target-repo
"""

import argparse
import json
import os
import subprocess
from dataclasses import asdict
from pathlib import Path

from .analyzers import discover_analyzers
from .analyzers.base import AnalysisResult


# ---------------------------------------------------------------------------
# Git helpers
# ---------------------------------------------------------------------------


def git(repo: Path, cmd: list[str]) -> str:
    try:
        return subprocess.check_output(
            ["git", "-C", str(repo)] + cmd,
            text=True,
            stderr=subprocess.DEVNULL,
        ).strip()
    except Exception:
        return "?"


def git_state_section(repo: Path) -> str:
    """Generate a markdown section describing the repo's git state."""
    branch = git(repo, ["branch", "--show-current"]) or "(detached)"
    sha = git(repo, ["rev-parse", "--short", "HEAD"])

    staged = git(repo, ["diff", "--cached", "--name-only"])
    unstaged = git(repo, ["diff", "--name-only"])
    if staged == "?":
        staged = ""
    if unstaged == "?":
        unstaged = ""
    changed = sorted(set((staged + "\n" + unstaged).strip().splitlines()))
    changes_str = (
        "\n".join(f"  {f}" for f in changed) if changed else "  (none)"
    )

    log_lines = git(repo, ["log", "--oneline", "-5"]).splitlines()
    recent = (
        "\n".join(f"  {l}" for l in log_lines) if log_lines else "  (none)"
    )

    return f"""Branch: {branch} @ {sha}

### Uncommitted changes
{changes_str}

### Recent commits
{recent}"""


# ---------------------------------------------------------------------------
# Output writers
# ---------------------------------------------------------------------------


def write_graph_outputs(
    graph_dir: Path,
    nodes: list[dict],
    edges: list[dict],
    flows: dict[str, str],
) -> None:
    graph_dir.mkdir(parents=True, exist_ok=True)
    flows_dir = graph_dir / "flows"
    flows_dir.mkdir(exist_ok=True)

    (graph_dir / "nodes.json").write_text(
        json.dumps(nodes, indent=2), encoding="utf-8"
    )
    (graph_dir / "edges.json").write_text(
        json.dumps(edges, indent=2), encoding="utf-8"
    )

    # Clean old flow files
    for old in flows_dir.glob("*.yaml"):
        old.unlink()

    for feat_name, yaml_content in flows.items():
        (flows_dir / f"{feat_name}.yaml").write_text(yaml_content, encoding="utf-8")


def write_state_md(
    graph_dir: Path,
    repo_root: Path,
    state_sections: dict[str, str],
    flows: dict[str, str],
) -> None:
    flows_list = ", ".join(sorted(flows.keys())) if flows else "(none)"

    sections = [
        "# Repo State\n",
        "*Generated by `repo-graph-generate`. Regenerate: `repo-graph-generate --repo .`*\n",
        "---\n",
        "## Git State\n",
        git_state_section(repo_root),
    ]

    if state_sections:
        sections.append("\n---\n")
        for title, content in state_sections.items():
            sections.append(f"## {title}\n")
            sections.append(content)

    sections.append("\n---\n")
    sections.append(f"## Available Flows\n\n{flows_list}\n")

    (graph_dir / "state.md").write_text("\n".join(sections), encoding="utf-8")


# ---------------------------------------------------------------------------
# Auto-flow generation
# ---------------------------------------------------------------------------


def _auto_flows(nodes: list[dict], edges: list[dict]) -> dict[str, str]:
    """
    Generate flows automatically from route nodes by following handled_by edges.

    Trace: route → (handled_by) → handler module/package → (defines/contains/imports) → deeper.
    Avoids walking back to sibling routes.
    """
    from .analyzers.base import render_flow_yaml

    node_map = {n["id"]: n for n in nodes}

    # Forward adjacency: from → [(to, type)]
    fwd: dict[str, list[tuple[str, str]]] = {}
    for e in edges:
        fwd.setdefault(e["from"], []).append((e["to"], e["type"]))

    # Reverse handled_by: handler_module → [route] (for route→handler direction)
    rev_handled: dict[str, list[tuple[str, str]]] = {}
    for e in edges:
        if e["type"] == "handled_by":
            rev_handled.setdefault(e["to"], []).append((e["from"], "handles"))

    routes = [n for n in nodes if n["type"] == "route"]
    if not routes:
        return {}

    # Edge types worth following when building a flow (not back to routes)
    _FOLLOW_TYPES = {"handled_by", "defines", "contains", "imports", "calls", "uses"}

    flows: dict[str, str] = {}
    for route in routes:
        name = route["name"]
        slug = name.replace(" ", "_").replace("/", "_").strip("_").lower()
        slug = slug.replace(":", "").replace("{", "").replace("}", "")
        if not slug or slug in flows:
            continue

        steps = [{"id": route["id"], "type": route["type"]}]
        visited = {route["id"]}
        frontier = [route["id"]]

        for _ in range(4):  # max depth
            next_frontier = []
            for nid in frontier:
                for target, etype in fwd.get(nid, []):
                    if target in visited or etype not in _FOLLOW_TYPES:
                        continue
                    n = node_map.get(target)
                    if not n or n["type"] == "route":
                        continue  # don't walk into sibling routes
                    visited.add(target)
                    steps.append({"id": n["id"], "type": n["type"], "edge": etype})
                    next_frontier.append(target)
            frontier = next_frontier
            if not frontier:
                break

        if len(steps) > 1:
            flows[slug] = render_flow_yaml(
                slug,
                [{"name": slug, "steps": steps}],
            )

    return flows


# ---------------------------------------------------------------------------
# Main generation pipeline
# ---------------------------------------------------------------------------


def generate(repo_root: Path) -> tuple[list[dict], list[dict], dict[str, str]]:
    """
    Run all matching analyzers against a repo and produce graph data.

    Returns (nodes, edges, flows) as dicts ready for JSON serialization.
    """
    graph_dir = repo_root / ".ai" / "repo-graph"

    analyzers = discover_analyzers(repo_root)
    if not analyzers:
        print(f"No language analyzers matched for {repo_root}")
        write_graph_outputs(graph_dir, [], [], {})
        write_state_md(graph_dir, repo_root, {}, {})
        return [], [], {}

    detected = [type(a).__name__ for a in analyzers]
    print(f"Detected analyzers: {', '.join(detected)}")

    # Collect results from all analyzers
    all_nodes: list[dict] = []
    all_edges: list[dict] = []
    all_flows: dict[str, str] = {}
    all_state_sections: dict[str, str] = {}

    for analyzer in analyzers:
        result: AnalysisResult = analyzer.scan()
        all_nodes.extend(asdict(n) for n in result.nodes)
        all_edges.extend(
            {"from": e.from_id, "to": e.to_id, "type": e.type}
            for e in result.edges
        )
        all_flows.update(result.flows)
        all_state_sections.update(result.state_sections)

    # Deduplicate nodes by id (first wins)
    seen_ids: set[str] = set()
    deduped_nodes: list[dict] = []
    for node in all_nodes:
        if node["id"] not in seen_ids:
            seen_ids.add(node["id"])
            deduped_nodes.append(node)

    # Deduplicate edges by (from, to, type)
    seen_edges: set[tuple[str, str, str]] = set()
    deduped_edges: list[dict] = []
    for edge in all_edges:
        key = (edge["from"], edge["to"], edge["type"])
        if key not in seen_edges:
            seen_edges.add(key)
            deduped_edges.append(edge)

    # Auto-generate flows from route nodes if analyzers didn't provide any
    if not all_flows:
        all_flows = _auto_flows(deduped_nodes, deduped_edges)

    write_graph_outputs(graph_dir, deduped_nodes, deduped_edges, all_flows)
    write_state_md(graph_dir, repo_root, all_state_sections, all_flows)

    print(
        f"Generated repo graph — {len(deduped_nodes)} nodes, "
        f"{len(deduped_edges)} edges, {len(all_flows)} flows"
    )

    return deduped_nodes, deduped_edges, all_flows


def main():
    parser = argparse.ArgumentParser(description="Generate repo graph data")
    parser.add_argument(
        "--repo",
        default=os.environ.get("REPO_GRAPH_REPO", os.getcwd()),
        help="Path to the target repository",
    )
    args = parser.parse_args()
    generate(Path(args.repo).resolve())


if __name__ == "__main__":
    main()
