"""
repo-graph generator.

Orchestrates language-specific analyzers to produce:
  - nodes.json   — all discovered entities
  - edges.json   — directed relationships between entities
  - flows/*.yaml — end-to-end request paths per feature
  - state.md     — session-start snapshot

Usage:
    repo-graph-generate --repo /path/to/target-repo
"""

import argparse
import json
import os
import subprocess
from dataclasses import asdict
from pathlib import Path

from .analyzers import discover_analyzers
from .analyzers.base import AnalysisResult
from .config import load_config
from .discovery import build_index
from .test_edges import add_test_edges


# ---------------------------------------------------------------------------
# Git helpers
# ---------------------------------------------------------------------------


def git(repo: Path, cmd: list[str]) -> str:
    try:
        return subprocess.check_output(
            ["git", "-C", str(repo)] + cmd,
            text=True,
            stderr=subprocess.DEVNULL,
        ).strip()
    except Exception:
        return "?"


def git_state_section(repo: Path) -> str:
    """Generate a markdown section describing the repo's git state."""
    branch = git(repo, ["branch", "--show-current"]) or "(detached)"
    sha = git(repo, ["rev-parse", "--short", "HEAD"])

    staged = git(repo, ["diff", "--cached", "--name-only"])
    unstaged = git(repo, ["diff", "--name-only"])
    if staged == "?":
        staged = ""
    if unstaged == "?":
        unstaged = ""
    changed = sorted(set((staged + "\n" + unstaged).strip().splitlines()))
    changes_str = (
        "\n".join(f"  {f}" for f in changed) if changed else "  (none)"
    )

    log_lines = git(repo, ["log", "--oneline", "-5"]).splitlines()
    recent = (
        "\n".join(f"  {l}" for l in log_lines) if log_lines else "  (none)"
    )

    return f"""Branch: {branch} @ {sha}

### Uncommitted changes
{changes_str}

### Recent commits
{recent}"""


# ---------------------------------------------------------------------------
# Output writers
# ---------------------------------------------------------------------------


def write_graph_outputs(
    graph_dir: Path,
    nodes: list[dict],
    edges: list[dict],
    flows: dict[str, str],
) -> None:
    graph_dir.mkdir(parents=True, exist_ok=True)
    flows_dir = graph_dir / "flows"
    flows_dir.mkdir(exist_ok=True)

    (graph_dir / "nodes.json").write_text(
        json.dumps(nodes, indent=2), encoding="utf-8"
    )
    (graph_dir / "edges.json").write_text(
        json.dumps(edges, indent=2), encoding="utf-8"
    )

    # Clean old flow files
    for old in flows_dir.glob("*.yaml"):
        old.unlink()

    for feat_name, yaml_content in flows.items():
        (flows_dir / f"{feat_name}.yaml").write_text(yaml_content, encoding="utf-8")


def write_state_md(
    graph_dir: Path,
    repo_root: Path,
    state_sections: dict[str, str],
    flows: dict[str, str],
) -> None:
    flows_list = ", ".join(sorted(flows.keys())) if flows else "(none)"

    sections = [
        "# Repo State\n",
        "*Generated by `repo-graph-generate`. Regenerate: `repo-graph-generate --repo .`*\n",
        "---\n",
        "## Git State\n",
        git_state_section(repo_root),
    ]

    if state_sections:
        sections.append("\n---\n")
        for title, content in state_sections.items():
            sections.append(f"## {title}\n")
            sections.append(content)

    sections.append("\n---\n")
    sections.append(f"## Available Flows\n\n{flows_list}\n")

    (graph_dir / "state.md").write_text("\n".join(sections), encoding="utf-8")


# ---------------------------------------------------------------------------
# Cross-stack endpoint linking
# ---------------------------------------------------------------------------


def _normalize_path(path: str) -> str:
    """Normalize a URL path for matching: strip prefix, params, lowercase."""
    # Remove common prefixes
    for prefix in ("protected/", "api/protected/", "api/"):
        if path.startswith(prefix):
            path = path[len(prefix):]
            break
    # Collapse path params: :id, {id} → *
    import re
    path = re.sub(r":[^/]+|\{[^}]+\}", "*", path)
    return path.strip("/").lower()


def _link_endpoints_to_routes(
    nodes: list[dict], edges: list[dict]
) -> list[dict]:
    """
    Match dangling endpoint_* edge targets to existing route_* nodes.

    Frontend analyzers create 'calls' edges to endpoint_ANY_<path> IDs.
    Backend analyzers create route nodes with route_METHOD_<path> IDs.
    This function rewires the dangling edges to the actual route nodes.
    """
    node_ids = {n["id"] for n in nodes}

    # Build route lookup: normalized_path → [route_node_id, ...]
    route_lookup: dict[str, list[str]] = {}
    for n in nodes:
        if n["type"] != "route":
            continue
        # Route name is like "GET /groups" or "POST /group"
        name = n.get("name", "")
        parts = name.split(" ", 1)
        if len(parts) == 2:
            path = _normalize_path(parts[1])
        else:
            path = _normalize_path(name)
        route_lookup.setdefault(path, []).append(n["id"])

    # Find dangling edges and try to match
    linked = 0
    new_edges = []
    for edge in edges:
        if edge["to"] in node_ids:
            new_edges.append(edge)
            continue

        # Dangling edge — try to resolve endpoint_ANY_<path>
        target = edge["to"]
        if not target.startswith("endpoint_"):
            new_edges.append(edge)
            continue

        # Extract path from endpoint ID: endpoint_ANY_protected_groups → protected/groups
        path_part = target.split("_", 2)[-1] if target.count("_") >= 2 else ""
        path_normalized = _normalize_path(path_part.replace("_", "/"))

        matches = route_lookup.get(path_normalized, [])
        if matches:
            for route_id in matches:
                new_edges.append(
                    {"from": edge["from"], "to": route_id, "type": edge["type"]}
                )
                linked += 1
        else:
            # Keep the original dangling edge
            new_edges.append(edge)

    if linked:
        print(f"  Linked {linked} cross-stack endpoint→route edges")

    return new_edges


# ---------------------------------------------------------------------------
# File-anchor edge resolution (data_source → module)
# ---------------------------------------------------------------------------


# Node types that represent "module-level" anchors — preferred targets for
# file:: edges over fine-grained (class/function) nodes.
_MODULE_NODE_TYPES = {
    "py_module", "py_package",
    "go_module", "go_package",
    "rust_module", "rust_crate",
    "ts_module", "typescript_module",
    "react_module", "react_project",
    "vue_module", "vue_project",
    "angular_module", "angular_project",
    "java_package", "java_project",
    "scala_package", "scala_project",
    "clj_namespace", "clj_project",
    "csharp_namespace", "csharp_project",
    "ruby_file", "ruby_project",
    "php_namespace", "php_project",
    "swift_file", "swift_project",
    "cpp_source", "cpp_header",
    "dart_module", "dart_project", "flutter_project",
    "elixir_module", "elixir_project",
    "sol_contract", "sol_interface", "sol_library", "sol_project",
    "tf_module",
}


def _resolve_file_edges(
    nodes: list[dict], edges: list[dict]
) -> list[dict]:
    """
    Rewrite `file::<rel>` edge sources to the best matching graph node.

    data_sources analyzer emits edges like `file::src/app/users.py` → data_source_*.
    This finds the real module/package node for that path and rewrites the edge.
    Edges with no matching node are dropped (file exists but no other analyzer
    claimed it).
    """
    file_to_nodes: dict[str, list[dict]] = {}
    # Build a second index: dir -> [module-level nodes in that dir]
    dir_to_module_nodes: dict[str, list[dict]] = {}
    for n in nodes:
        fp = n.get("file_path", "")
        if not fp:
            continue
        file_to_nodes.setdefault(fp, []).append(n)
        if n["type"] in _MODULE_NODE_TYPES:
            parent = fp.rsplit("/", 1)[0] if "/" in fp else ""
            dir_to_module_nodes.setdefault(parent, []).append(n)

    def _best_for(file_rel: str) -> dict | None:
        # 1. Module-level node on the exact file
        candidates = file_to_nodes.get(file_rel, [])
        mods = [c for c in candidates if c["type"] in _MODULE_NODE_TYPES]
        if mods:
            return mods[0]
        # 2. Walk up the directory tree looking for a module-level node
        parent = file_rel.rsplit("/", 1)[0] if "/" in file_rel else ""
        while parent:
            dir_mods = dir_to_module_nodes.get(parent, [])
            if dir_mods:
                return dir_mods[0]
            if "/" not in parent:
                break
            parent = parent.rsplit("/", 1)[0]
        # 3. Root-level module node
        root_mods = dir_to_module_nodes.get("", [])
        if root_mods:
            return root_mods[0]
        # 4. Any node on the exact file (fine-grained fallback)
        return candidates[0] if candidates else None

    resolved = 0
    dropped = 0
    new_edges: list[dict] = []
    for edge in edges:
        src = edge["from"]
        dst = edge["to"]
        src_is_anchor = src.startswith("file::")
        dst_is_anchor = dst.startswith("file::")
        if not src_is_anchor and not dst_is_anchor:
            new_edges.append(edge)
            continue

        new_src, new_dst = src, dst
        if src_is_anchor:
            pick = _best_for(src[len("file::"):])
            if pick is None:
                dropped += 1
                continue
            new_src = pick["id"]
        if dst_is_anchor:
            pick = _best_for(dst[len("file::"):])
            if pick is None:
                dropped += 1
                continue
            new_dst = pick["id"]

        new_edges.append({"from": new_src, "to": new_dst, "type": edge["type"]})
        resolved += 1

    if resolved or dropped:
        print(f"  Resolved {resolved} file-anchor edges ({dropped} dropped)")

    return new_edges


# ---------------------------------------------------------------------------
# Confidence scoring
# ---------------------------------------------------------------------------


_WEAK_PATH_MARKERS = (
    "/test/", "/tests/", "/spec/", "/specs/",
    "/example/", "/examples/", "/sample/", "/samples/",
    "/demo/", "/demos/", "/fixture/", "/fixtures/",
    "/__tests__/", "/__mocks__/",
)
_WEAK_FILENAME_MARKERS = (
    "_test.", ".test.", "_spec.", ".spec.", "test_", "_tests.",
)

_CONFIDENCE_ORDER = {"weak": 0, "medium": 1, "strong": 2}


def _path_is_weak(file_path: str) -> bool:
    rel = "/" + file_path.replace("\\", "/").lstrip("/")
    if any(marker in rel for marker in _WEAK_PATH_MARKERS):
        return True
    basename = rel.rsplit("/", 1)[-1].lower()
    return any(marker in basename for marker in _WEAK_FILENAME_MARKERS)


def _score_confidence(nodes: list[dict], edges: list[dict]) -> None:
    """In-place: set node['confidence'] based on file path + handler resolution.

    Rules:
      - file_path under test/example/spec/demo → weak
      - route with a handled_by edge to a real handler node → strong
      - otherwise medium
    """
    node_map = {n["id"]: n for n in nodes}

    # Pass 1 — downgrade test/example paths
    for n in nodes:
        fp = n.get("file_path") or ""
        if fp and _path_is_weak(fp):
            n["confidence"] = "weak"

    # Pass 2 — upgrade routes whose handler resolves to a real node
    for e in edges:
        if e["type"] != "handled_by":
            continue
        route = node_map.get(e["from"])
        handler = node_map.get(e["to"])
        if route is None or handler is None:
            continue
        if route["type"] != "route":
            continue
        if route.get("confidence") == "weak":
            continue  # don't override weak
        # Handler must be a concrete code node, not another route
        if handler["type"] == "route":
            continue
        route["confidence"] = "strong"


def _flow_confidence(steps: list[dict], node_map: dict[str, dict]) -> str:
    """Overall flow confidence = min(step confidences)."""
    tiers = []
    for step in steps:
        node = node_map.get(step["id"])
        if node is None:
            continue
        tiers.append(node.get("confidence", "medium"))
    if not tiers:
        return "medium"
    return min(tiers, key=lambda t: _CONFIDENCE_ORDER.get(t, 1))


# ---------------------------------------------------------------------------
# Auto-flow generation
# ---------------------------------------------------------------------------


def _auto_flows(nodes: list[dict], edges: list[dict]) -> dict[str, str]:
    """
    Generate flows automatically from route nodes by following handled_by edges.

    Trace: route → (handled_by) → handler module/package → (defines/contains/imports) → deeper.
    Avoids walking back to sibling routes.
    """
    from .analyzers.base import render_flow_yaml

    node_map = {n["id"]: n for n in nodes}

    # Forward adjacency: from → [(to, type)]
    fwd: dict[str, list[tuple[str, str]]] = {}
    for e in edges:
        fwd.setdefault(e["from"], []).append((e["to"], e["type"]))

    # Reverse handled_by: handler_module → [route] (for route→handler direction)
    rev_handled: dict[str, list[tuple[str, str]]] = {}
    for e in edges:
        if e["type"] == "handled_by":
            rev_handled.setdefault(e["to"], []).append((e["from"], "handles"))

    # Entrypoint types seed flows; their type determines the flow `kind`
    _ENTRYPOINT_KIND = {
        "route": "http",                # page/http distinguished by name below
        "cli_command": "cli",
        "grpc_method": "grpc",
        "queue_consumer": "queue",
    }
    entrypoints = [n for n in nodes if n["type"] in _ENTRYPOINT_KIND]
    if not entrypoints:
        return {}

    # Edge types worth following when building a flow (not back to sibling entrypoints)
    _FOLLOW_TYPES = {"handled_by", "defines", "contains", "imports", "calls", "uses"}

    flows: dict[str, str] = {}
    for entry in entrypoints:
        name = entry["name"]
        slug = name.replace(" ", "_").replace("/", "_").strip("_").lower()
        slug = slug.replace(":", "").replace("{", "").replace("}", "")
        if not slug or slug in flows:
            continue

        steps = [{"id": entry["id"], "type": entry["type"]}]
        visited = {entry["id"]}
        frontier = [entry["id"]]

        for _ in range(4):  # max depth
            next_frontier = []
            for nid in frontier:
                for target, etype in fwd.get(nid, []):
                    if target in visited or etype not in _FOLLOW_TYPES:
                        continue
                    n = node_map.get(target)
                    if not n or n["type"] in _ENTRYPOINT_KIND:
                        continue  # don't walk into sibling entrypoints
                    visited.add(target)
                    steps.append({"id": n["id"], "type": n["type"], "edge": etype})
                    next_frontier.append(target)
            frontier = next_frontier
            if not frontier:
                break

        if len(steps) > 1:
            base_kind = _ENTRYPOINT_KIND[entry["type"]]
            if entry["type"] == "route" and entry["name"].startswith("PAGE "):
                base_kind = "page"
            kind = base_kind
            confidence = _flow_confidence(steps, node_map)
            flows[slug] = render_flow_yaml(
                slug,
                [{"name": slug, "steps": steps}],
                kind=kind,
                confidence=confidence,
            )

    return flows


# ---------------------------------------------------------------------------
# Main generation pipeline
# ---------------------------------------------------------------------------


def generate(repo_root: Path) -> tuple[list[dict], list[dict], dict[str, str]]:
    """
    Run all matching analyzers against a repo and produce graph data.

    Returns (nodes, edges, flows) as dicts ready for JSON serialization.
    """
    graph_dir = repo_root / ".ai" / "repo-graph"

    config = load_config(repo_root)
    if config.skip or config.roots:
        print(
            f"  [config] skip={sorted(config.skip) or '[]'} "
            f"roots={ {k: len(v) for k, v in config.roots.items()} or '{}'}"
        )
    index = build_index(
        repo_root,
        extra_skip=config.skip,
        config_roots=config.roots,
    )
    analyzers = discover_analyzers(repo_root, index)
    if not analyzers:
        print(f"No language analyzers matched for {repo_root}")
        write_graph_outputs(graph_dir, [], [], {})
        write_state_md(graph_dir, repo_root, {}, {})
        return [], [], {}

    detected = [type(a).__name__ for a in analyzers]
    print(f"Detected analyzers: {', '.join(detected)}")

    # Collect results from all analyzers
    all_nodes: list[dict] = []
    all_edges: list[dict] = []
    all_flows: dict[str, str] = {}
    all_state_sections: dict[str, str] = {}

    for analyzer in analyzers:
        result: AnalysisResult = analyzer.scan()
        all_nodes.extend(asdict(n) for n in result.nodes)
        all_edges.extend(
            {"from": e.from_id, "to": e.to_id, "type": e.type}
            for e in result.edges
        )
        all_flows.update(result.flows)
        all_state_sections.update(result.state_sections)

    # Deduplicate nodes by id (first wins)
    seen_ids: set[str] = set()
    deduped_nodes: list[dict] = []
    for node in all_nodes:
        if node["id"] not in seen_ids:
            seen_ids.add(node["id"])
            deduped_nodes.append(node)

    # Deduplicate edges by (from, to, type)
    seen_edges: set[tuple[str, str, str]] = set()
    deduped_edges: list[dict] = []
    for edge in all_edges:
        key = (edge["from"], edge["to"], edge["type"])
        if key not in seen_edges:
            seen_edges.add(key)
            deduped_edges.append(edge)

    # Link cross-stack endpoints to backend routes
    deduped_edges = _link_endpoints_to_routes(deduped_nodes, deduped_edges)

    # Resolve file::<rel> anchors (from data_sources analyzer) to real nodes
    deduped_edges = _resolve_file_edges(deduped_nodes, deduped_edges)

    # Deduplicate edges again after rewrites
    seen_edges_2: set[tuple[str, str, str]] = set()
    final_edges: list[dict] = []
    for edge in deduped_edges:
        key = (edge["from"], edge["to"], edge["type"])
        if key not in seen_edges_2:
            seen_edges_2.add(key)
            final_edges.append(edge)
    deduped_edges = final_edges

    # Score node confidence based on file path + handler resolution
    _score_confidence(deduped_nodes, deduped_edges)

    # Emit test_file nodes + `tests` edges for detected test files
    add_test_edges(deduped_nodes, deduped_edges, index)

    # Rebuild flows with cross-stack edges included
    all_flows = _auto_flows(deduped_nodes, deduped_edges)

    write_graph_outputs(graph_dir, deduped_nodes, deduped_edges, all_flows)
    write_state_md(graph_dir, repo_root, all_state_sections, all_flows)

    print(
        f"Generated repo graph — {len(deduped_nodes)} nodes, "
        f"{len(deduped_edges)} edges, {len(all_flows)} flows"
    )

    return deduped_nodes, deduped_edges, all_flows


def main():
    parser = argparse.ArgumentParser(description="Generate repo graph data")
    parser.add_argument(
        "--repo",
        default=os.environ.get("REPO_GRAPH_REPO", os.getcwd()),
        help="Path to the target repository",
    )
    args = parser.parse_args()
    generate(Path(args.repo).resolve())


if __name__ == "__main__":
    main()
